[build]
target = "x86_64-stom-none.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.'cfg(target_os = "linux")']
rustflags=["-C", "link-arg=-nostartfiles"]
